/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dinosauri;

import java.util.ArrayList;

/**
 *
 * @author polenzani.pietro
 */
public class Interfaccia extends javax.swing.JFrame {
    Gestore gestore = new Gestore();
    

    /**
     * Creates new form Interfaccia
     */
    public Interfaccia() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_calcolaPunti = new javax.swing.JButton();
        btn_giocaCarta = new javax.swing.JButton();
        btn_avviaPartita = new javax.swing.JButton();
        btn_partitaRapida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_punteggioG2 = new javax.swing.JLabel();
        lbl_punteggioG1 = new javax.swing.JLabel();
        lbl_vincitore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_calcolaPunti.setText("calcola punti");
        btn_calcolaPunti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcolaPuntiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_calcolaPunti, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, 50));
        btn_calcolaPunti.getAccessibleContext().setAccessibleName("btn_calcolaPunti");

        btn_giocaCarta.setText("gioca carta");
        jPanel1.add(btn_giocaCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 50));
        btn_giocaCarta.getAccessibleContext().setAccessibleName("btn_giocaCarta");

        btn_avviaPartita.setText("avvia partita");
        btn_avviaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avviaPartitaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_avviaPartita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 50));

        btn_partitaRapida.setText("partita rapida");
        btn_partitaRapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_partitaRapidaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_partitaRapida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 270));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("GIOCO DEL DINOSAURO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 540, 220));

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("GIOCATORE 1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("GIOCATORE 2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 120, -1));

        jLabel4.setText("PUNTEGGIO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 70, 20));

        jLabel5.setText("PUNTEGGIO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 20));

        lbl_punteggioG2.setText("0");
        jPanel2.add(lbl_punteggioG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 10, 20));

        lbl_punteggioG1.setText("0");
        jPanel2.add(lbl_punteggioG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 10, 20));
        jPanel2.add(lbl_vincitore, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 460, 140));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 800, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_avviaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avviaPartitaActionPerformed
    }//GEN-LAST:event_btn_avviaPartitaActionPerformed

    private void btn_calcolaPuntiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcolaPuntiActionPerformed
        lbl_punteggioG1.setText(String.valueOf(gestore.calcolaPunteggioGiocatore(gestore.g1)));
        lbl_punteggioG2.setText(String.valueOf(gestore.calcolaPunteggioGiocatore(gestore.g2)));
    }//GEN-LAST:event_btn_calcolaPuntiActionPerformed

    private void btn_partitaRapidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_partitaRapidaActionPerformed
        lbl_vincitore.setText("il vincitore è "+ gestore.partitaRapida(gestore.g1, gestore.g2));
    }//GEN-LAST:event_btn_partitaRapidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaccia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avviaPartita;
    private javax.swing.JButton btn_calcolaPunti;
    private javax.swing.JButton btn_giocaCarta;
    private javax.swing.JButton btn_partitaRapida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_punteggioG1;
    private javax.swing.JLabel lbl_punteggioG2;
    private javax.swing.JLabel lbl_vincitore;
    // End of variables declaration//GEN-END:variables
}
